﻿
document.write('<!-- 用来产生编辑状态的ActiveX控件的JS脚本-->   ');
document.write('<!-- 因为微软的ActiveX新机制，需要一个外部引入的js-->   ');
document.write('<object id="TANGER_OCX" classid="clsid:C9BC4DFF-4248-4a3c-8A49-63A7D317F404"    ');
document.write('codebase="officecontrol/OfficeControl.cab#version=5,0,2,2" width="100%" height="600">   ');
document.write('<param name="MakerCaption" value="南昌恩优科技有限公司">   ');
document.write('<param name="MakerKey" value="78735CE1985CE980BB015BD8AD3A60D4AFC9762">   ');
document.write('<param name="ProductCaption" value="中国移动通信集团江西有限公司">   ');
document.write('<param name="ProductKey" value="91D4C66BB6F82FF7715A9558A1132F3E4E6E4888">   ');
document.write('<param name="IsUseUTF8URL" value="-1">   ');
document.write('<param name="IsUseUTF8Data" value="-1">   ');
document.write('<param name="BorderStyle" value="1">   ');
document.write('<param name="Hidden2003Menus" value="表格(&A);格式(&O);视图(&V);">');
document.write('<param name="BorderColor" value="14402205">   ');
document.write('<param name="TitlebarColor" value="15658734">   ');
document.write('<param name="TitlebarTextColor" value="0">   ');
document.write('<param name="MenubarColor" value="14402205">   ');
document.write('<param name="MenuButtonColor" VALUE="16180947">   ');
document.write('<param name="MenuBarStyle" value="3">   ');
document.write('<param name="MenuButtonStyle" value="7">   ');
document.write('<param name="WebUserName" value="NTKO">   ');
document.write('<param name="Caption" value="欢迎!">   ');
document.write('<SPAN STYLE="color:red">不能装载文档控件。请在检查浏览器的选项中检查浏览器的安全设置。</SPAN>   ');
document.write('</object>');
